#######################################################################################
# Book settings
title                         : Template NTFPS evaluation
author                        : Andrew McCarthy
logo                          : 'logo.png'
email                         : andrew2.mccarthy@northumbria.ac.uk
description: >-
  This book is a template for NENCARC NTFPS evaluation
  
  execute_notebooks           : cache


html:
  favicon                     : 'favicon.png'
  home_page_in_navbar         : false
  use_edit_page_button        : true
  use_repository_button       : true
  use_issue_button            : true


repository:
  url                         : https://github.com/nencarc-digital/template/
  branch                      : master
  path_to_book                : book


# launch_buttons:
  # notebook_interface          : classic
  # binderhub_url               : "https://mybinder.org"
  # colab_url                   : "https://colab.research.google.com"
  # thebe                       : true
